image:
  repository: ghcr.io/sozercan/llama3
  tag: "8b"
  pullPolicy: IfNotPresent

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 999
  supplementalGroups:
    - 999

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false # aikit extracts backends during runtime
  runAsGroup: 999
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    memory: 8Gi
    # nvidia.com/gpu: "1"
  requests:
    cpu: 100m
    memory: 128Mi
    # nvidia.com/gpu: "1"

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

affinity: {}

rbac:
  create: true

enableRuntimeDefaultSeccompProfile: true
postInstall:
  resources: {}
  affinity: {}
  tolerations: []
  nodeSelector: {kubernetes.io/os: linux}
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsGroup: 999
    runAsNonRoot: true
    runAsUser: 1000
  labelNamespace:
    enabled: true
    image:
      repository: registry.k8s.io/kubectl
      tag: v1.31.2
      pullPolicy: IfNotPresent
      pullSecrets: []
    podSecurity: ["pod-security.kubernetes.io/audit=restricted",
      "pod-security.kubernetes.io/audit-version=latest",
      "pod-security.kubernetes.io/warn=restricted",
      "pod-security.kubernetes.io/warn-version=latest",
      "pod-security.kubernetes.io/enforce=restricted",
      "pod-security.kubernetes.io/enforce-version=v1.30"]
    extraAnnotations: {}
    extraRules: []
    priorityClassName: ""
