FROM fedora:44@sha256:6c75d5bf57cb0fa5aa4b92c6a83c86c791644496d9ac230de7711f5b8ec3b898

ARG MESA_VERSION="24.1.2-101"

USER 0

# Install the patched mesa-krunkit drivers
RUN dnf -y install dnf-plugins-core && \
    dnf -y copr enable slp/mesa-krunkit epel-9-aarch64 && \
    dnf -y install \
        mesa-vulkan-drivers-$MESA_VERSION.el9.aarch64 && \
    dnf clean all
