FROM fedora:44@sha256:498c452f32a739b61f0ef215bce9924ebc4866cbe44710f58157d77723b7a6d2

ARG MESA_VERSION="24.1.2-101"

USER 0

# Install the patched mesa-krunkit drivers
RUN dnf -y install dnf-plugins-core && \
    dnf -y copr enable slp/mesa-krunkit epel-9-aarch64 && \
    dnf -y install \
        mesa-vulkan-drivers-$MESA_VERSION.el9.aarch64 && \
    dnf clean all
