ARG UBUNTU_RELEASE=22.04

FROM golang:1.26-bookworm@sha256:116d58cbd88c1297624acc6e967a060012422bacf9930927e23fb719189c6f36 AS builder
ARG UBUNTU_RELEASE
ARG TARGETARCH

RUN go install github.com/canonical/chisel/cmd/chisel@v1.0.0

RUN mkdir -p /rootfs && chisel cut --release ubuntu-$UBUNTU_RELEASE --root /rootfs \
    base-files_base \
    base-files_chisel \
    base-files_release-info \
    ca-certificates_data \
    libgcc-s1_libs \
    libc6_libs \
    bash_bins \
    coreutils_bins \
    grep_bins

FROM scratch
COPY --from=builder /rootfs /
