ARG UBUNTU_RELEASE=22.04

FROM golang:1.27-bookworm@sha256:648f440f42a0958804efb24df176f806f9d353b41f1c0627f666428e40310f6b AS builder
ARG UBUNTU_RELEASE
ARG TARGETARCH

RUN go install github.com/canonical/chisel/cmd/chisel@v1.0.0

RUN mkdir -p /rootfs && chisel cut --release ubuntu-$UBUNTU_RELEASE --root /rootfs \
    base-files_base \
    base-files_chisel \
    base-files_release-info \
    ca-certificates_data \
    libgcc-s1_libs \
    libc6_libs \
    bash_bins \
    coreutils_bins \
    grep_bins

FROM scratch
COPY --from=builder /rootfs /
