apiVersion: v1
entries:
  aikit:
  - apiVersion: v2
    appVersion: v0.9.0
    created: "2024-05-30T21:53:53.832206301Z"
    description: Kubernetes Helm chart to deploy AIKit LLM images
    digest: bc1ea7f1a093bea613dd7cf792ce919794001492cd4fcf03c30c5e177f2f40c9
    name: aikit
    type: application
    urls:
    - https://sozercan.github.io/aikit/charts/aikit-0.9.0.tgz
    version: 0.9.0
generated: "2024-05-30T21:53:53.830708008Z"
