apiVersion: v1
entries:
  aikit:
  - apiVersion: v2
    appVersion: v0.11.1
    created: "2024-06-13T05:44:20.458373774Z"
    description: Kubernetes Helm chart to deploy AIKit LLM images
    digest: fe5fc0b11a20f6c9d4688000cabb155147d8e9e29c2b4b3c16ff37a277970c04
    name: aikit
    type: application
    urls:
    - https://sozercan.github.io/aikit/charts/aikit-0.11.1.tgz
    version: 0.11.1
  - apiVersion: v2
    appVersion: v0.11.0
    created: "2024-06-13T03:49:04.209630378Z"
    description: Kubernetes Helm chart to deploy AIKit LLM images
    digest: d2f5c8786430045687f81ddcb8628eb55bd33ae910cba1be743d0d01e4ed3c39
    name: aikit
    type: application
    urls:
    - https://sozercan.github.io/aikit/charts/aikit-0.11.0.tgz
    version: 0.11.0
  - apiVersion: v2
    appVersion: v0.10.0
    created: "2024-06-06T11:11:44.855353505Z"
    description: Kubernetes Helm chart to deploy AIKit LLM images
    digest: cca85f5cd3a4ff216a78c1d87e92e94feefd1007157e76ed2ffd34aa92ca005c
    name: aikit
    type: application
    urls:
    - https://sozercan.github.io/aikit/charts/aikit-0.10.0.tgz
    version: 0.10.0
  - apiVersion: v2
    appVersion: v0.9.0
    created: "2024-05-30T21:53:53.832206301Z"
    description: Kubernetes Helm chart to deploy AIKit LLM images
    digest: bc1ea7f1a093bea613dd7cf792ce919794001492cd4fcf03c30c5e177f2f40c9
    name: aikit
    type: application
    urls:
    - https://sozercan.github.io/aikit/charts/aikit-0.9.0.tgz
    version: 0.9.0
generated: "2024-06-13T05:44:20.457751279Z"
