name: dev

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
 release:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tag
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Push aikit to GHCR
        run: |
          docker buildx build -t ghcr.io/sozercan/aikit:dev --push .

      - name: release llama 2 image
        run: |
          docker buildx build -t ghcr.io/sozercan/llama2:dev -f test/aikitfile-dev.yaml --push --cache-from=type=gha,scope=llama-2-7b-chat --cache-to=type=gha,scope=llama-2-7b-chat,mode=max
