name: patch-models
on:
  # patch weekly
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
    patch-models:
        runs-on: ubuntu-latest
        timeout-minutes: 240
        strategy:
          fail-fast: false
          matrix:
            images:
              - ghcr.io/sozercan/llama2:7b
              - ghcr.io/sozercan/llama2:7b-cuda
              - ghcr.io/sozercan/llama2:13b
              - ghcr.io/sozercan/llama2:13b-cuda
              - ghcr.io/sozercan/orca2:13b
              - ghcr.io/sozercan/orca2:13b-cuda
              - ghcr.io/sozercan/mixtral:8x7b
              - ghcr.io/sozercan/mixtral:8x7b-cuda
              - ghcr.io/sozercan/phi2:2.7b
              - ghcr.io/sozercan/phi2:2.7b-cuda

        steps:
        - uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
          with:
            tool-cache: true
            android: true
            dotnet: true
            haskell: true
            large-packages: true
            docker-images: true
            swap-storage: true

        - name: Harden Runner
          uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
          with:
            egress-policy: audit

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

        - name: Login to GHCR
          uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Generate Trivy Report
          uses: aquasecurity/trivy-action@d43c1f16c00cfd3978dde6c07f4bbcf9eb6993ca # 0.16.1
          with:
            timeout: 60m
            scan-type: 'image'
            format: 'json'
            output: 'report.json'
            ignore-unfixed: true
            vuln-type: 'os'
            image-ref: ${{ matrix.images }}

        - name: Check vulnerability count
          id: vuln_count
          run: |
            cat report.json | jq
            vuln_count=$(jq '.Results[0].Vulnerabilities | length' report.json)
            echo "vuln_count=$vuln_count" >> $GITHUB_OUTPUT

        - name: Get image tag
          run: |
            image_tag=$(echo ${{ matrix.images }} | cut -d':' -f2)
            echo $image_tag
            echo "image_tag=$image_tag" >> $GITHUB_ENV

        - name: Copa Action
          if: steps.vuln_count.outputs.vuln_count != '0'
          id: copa
          uses: project-copacetic/copa-action@9a4406210914e570a473abf3f1e6c4fd952c7749 # v1.1.0
          with:
            image: ${{ matrix.images }}
            image-report: 'report.json'
            patched-tag: ${image_tag}
            timeout: 30m

        - name: Install Cosign
          if: steps.copa.conclusion == 'success'
          uses: sigstore/cosign-installer@e1523de7571e31dbe865fd2e80c5c7c23ae71eb4 # v3.4.0

        - name: Docker Push Patched Image
          id: push
          if: steps.copa.conclusion == 'success'
          run: |
            docker tag ${{ steps.copa.outputs.patched-image }} ${{ matrix.images }}
            docker images
            docker push ${{ matrix.images }}
            echo "DIGEST=$(cosign triangulate ${{ matrix.images }} --type digest)" >> $GITHUB_ENV

        - name: Sign the images with GitHub OIDC Token
          id: sign
          if: steps.push.conclusion == 'success'
          run: cosign sign --yes ${DIGEST}

        - name: Verify image signature
          if: steps.sign.conclusion == 'success'
          run: |
            cosign verify ${DIGEST} \
              --certificate-oidc-issuer https://token.actions.githubusercontent.com \
              --certificate-identity-regexp 'https://github\.com/sozercan/aikit/\.github/workflows/.+'
