name: release-base

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch: # used for testing

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  release-base:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    strategy:
      fail-fast: true
      matrix:
        runtime:
          - base
          - applesilicon
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Install Cosign
        uses: sigstore/cosign-installer@3454372f43399081ed03b604cb2d021dabca52bb # v3.8.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Login to GHCR
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set runtime variables for matrix
        run: |
          if [ ${{ matrix.runtime }} == "base" ]; then
            echo PLATFORMS="linux/amd64,linux/arm64" >> $GITHUB_ENV
            echo FILE="Dockerfile.base" >> $GITHUB_ENV
            echo TAG="ghcr.io/sozercan/base:latest" >> $GITHUB_ENV
            echo CACHE_FROM="type=gha,scope=base" >> $GITHUB_ENV
            echo CACHE_TO="type=gha,scope=base,mode=max" >> $GITHUB_ENV
          elif [ ${{ matrix.runtime }} == "applesilicon" ]; then
            echo PLATFORMS="linux/arm64" >> $GITHUB_ENV
            echo FILE="Dockerfile.base-applesilicon" >> $GITHUB_ENV
            echo TAG="ghcr.io/sozercan/applesilicon/base:latest" >> $GITHUB_ENV
            echo CACHE_FROM="type=gha,scope=base-applesilicon" >> $GITHUB_ENV
            echo CACHE_TO="type=gha,scope=base-applesilicon,mode=max" >> $GITHUB_ENV
          fi

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        id: build-and-push
        with:
          push: true
          sbom: true
          provenance: true
          tags: ${{ env.TAG }}
          cache-from: ${{ env.CACHE_FROM }}
          cache-to: ${{ env.CACHE_TO }}
          platforms: ${{ env.PLATFORMS }}
          file: ${{ env.FILE }}

      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: cosign sign --yes "ghcr.io/sozercan/base@${DIGEST}"

      - name: Verify image signature
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: |
          cosign verify ghcr.io/sozercan/base@${DIGEST} \
            --certificate-oidc-issuer https://token.actions.githubusercontent.com \
            --certificate-identity https://github.com/sozercan/aikit/.github/workflows/release-base.yaml@refs/heads/main
