name: release-pr
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.0' # run this workflow when a new minor version is published
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Which version are we creating a release pull request for?'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Set release version and target branch for main branch
        if: github.event_name == 'push'
        run: |
          TAG="$(echo "${{ github.ref }}" | tr -d 'refs/tags/v')"
          MAJOR_VERSION="$(echo "${TAG}" | cut -d '.' -f1)"
          echo "MAJOR_VERSION=${MAJOR_VERSION}" >> ${GITHUB_ENV}
          MINOR_VERSION="$(echo "${TAG}" | cut -d '.' -f2)"
          echo "MINOR_VERSION=${MINOR_VERSION}" >> ${GITHUB_ENV}

          echo "NEWVERSION=v${MAJOR_VERSION}.${MINOR_VERSION}.0" >> ${GITHUB_ENV}
          # push is always being merged to the main branch
          echo "TARGET_BRANCH=main" >> ${GITHUB_ENV}
          echo "TAG=${TAG}" >> ${GITHUB_ENV}

      - name: Set release version and target branch from input
        if: github.event_name == 'workflow_dispatch'
        run: |
          NEWVERSION="${{ github.event.inputs.release_version }}"
          echo "${NEWVERSION}" | grep -E '^v[0-9]+\.[0-9]+\.[0-9](-(beta|rc)\.[0-9]+)?$' || (echo "release_version should be in the format vX.Y.Z, vX.Y.Z-beta.A, or vX.Y.Z-rc.B" && exit 1)

          echo "NEWVERSION=${NEWVERSION}" >> ${GITHUB_ENV}
          echo "TAG=${NEWVERSION}" >> ${GITHUB_ENV}
          MAJOR_VERSION="$(echo "${NEWVERSION}" | cut -d '.' -f1 | tr -d 'v')"
          MINOR_VERSION="$(echo "${NEWVERSION}" | cut -d '.' -f2)"

          # non-beta releases should always be merged to release branches
          echo "TARGET_BRANCH=release-${MAJOR_VERSION}.${MINOR_VERSION}" >> ${GITHUB_ENV}

          # beta releases should always be merged to main
          if [[ "${NEWVERSION}" =~ "beta" ]]; then
            echo "TARGET_BRANCH=main" >> ${GITHUB_ENV}
          fi

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0

      - name: Create release branch if needed
        run: |
          git checkout "${TARGET_BRANCH}" && exit 0

          # Create and push release branch if it doesn't exist
          git checkout -b "${TARGET_BRANCH}"
          git push --set-upstream origin "${TARGET_BRANCH}"

      - run: make release-manifest

      - name: Create release pull request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
        with:
          commit-message: "chore: Prepare ${{ env.NEWVERSION }} release"
          title: "chore: Prepare ${{ env.NEWVERSION }} release"
          branch: "release-${{ env.NEWVERSION }}"
          base: "${{ env.TARGET_BRANCH }}"
          signoff: true
          labels: |
            release-pr
            ${{ github.event.inputs.release_version }}
