name: release

on:
  push:
    tags:
      - v*

permissions:
  contents: write
  packages: write

jobs:
 release:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tag
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Push aikit to GHCR
        run: |
          docker buildx build -t ghcr.io/sozercan/aikit:${TAG} --push .
          docker tag ghcr.io/sozercan/aikit:${TAG} ghcr.io/sozercan/aikit:latest
          docker push ghcr.io/sozercan/aikit:latest

      - name: release llama 2 image
        run: |
          docker buildx build -t ghcr.io/sozercan/llama2:7b -t ghcr.io/sozercan/llama2:7b-chat -t ghcr.io/sozercan/llama2:chat -t ghcr.io/sozercan/llama2:latest -f models/llama-2-chat-7b.yaml --push --cache-from=type=gha,scope=llama-2-7b-chat --cache-to=type=gha,scope=llama-2-7b-chat,mode=max
