name: kubernetes-test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'website/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'website/**'

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
      - uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Harden Runner
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: block
          allowed-endpoints: >
            auth.docker.io:443
            huggingface.co:443
            *.huggingface.co:443
            *.hf.co:443
            cdn.dl.k8s.io:443
            dl.k8s.io:443
            download.docker.com:443
            gcr.io:443
            github.com:443
            *.githubusercontent.com:443
            production.cloudflare.docker.com:443
            proxy.golang.org:443
            registry-1.docker.io:443
            storage.googleapis.com:443
            *.ubuntu.com:80
            developer.download.nvidia.com:443
            get.helm.sh:443
            *.blob.core.windows.net:443
            *.azureedge.net:443
            ghcr.io:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # need containerd image store for testing local images
      - uses: crazy-max/ghaction-setup-docker@b60f85385d03ac8acfca6d9996982511d8620a19 # v4.3.0
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - uses: crazy-max/ghaction-github-runtime@3cb05d89e1f492524af3d41a1c98c83bc3025124 # v3.1.0

      - name: build aikit
        run: |
          docker buildx build . -t aikit:test \
            --load --provenance=false --progress plain \
            --cache-from=type=gha,scope=aikit-amd64 \
            --cache-to=type=gha,scope=aikit-amd64,mode=max

      - name: build test model
        run: |
          docker buildx build . -t testmodel:test \
            -f test/aikitfile-llama.yaml \
            --load --provenance=false --progress plain \
            --cache-from=type=gha,scope=testmodel-amd64 \
            --cache-to=type=gha,scope=testmodel-amd64,mode=max

      - name: list images
        run: docker images

      - name: install e2e dependencies
        run: make test-e2e-dependencies

      - name: create kind cluster
        run: kind create cluster --wait 5m

      - name: load test model image into kind cluster
        run: kind load docker-image testmodel:test

      - name: deploy test model
        run: |
          kubectl create deployment test-model-deployment --image=testmodel:test --replicas 1
          kubectl rollout status deployment test-model-deployment
          kubectl expose deployment test-model-deployment --port=8080 --target-port=8080 --name=test-model-service
          kubectl port-forward service/test-model-service 8080:8080 &

      - name: run test
        run: |
          result=$(curl --fail --retry 10 --retry-all-errors http://127.0.0.1:8080/v1/chat/completions -H "Content-Type: application/json" -d '{
            "model": "llama-3.2-1b-instruct",
            "messages": [{"role": "user", "content": "explain kubernetes in a sentence"}]
          }')
          echo $result

          choices=$(echo "$result" | jq '.choices')
          if [ -z "$choices" ]; then
            exit 1
          fi

      - name: save logs
        if: always()
        run: |
          echo "KIND_LOGS_PATH=$(kind export logs)" >> $GITHUB_ENV

      - name: publish logs
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: kind-logs
          path: $KIND_LOGS_PATH
