name: helm-test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'website/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'website/**'

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
      - uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Harden Runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        with:
          egress-policy: block
          allowed-endpoints: >
            auth.docker.io:443
            *.huggingface.co:443
            cdn.dl.k8s.io:443
            dl.k8s.io:443
            download.docker.com:443
            gcr.io:443
            github.com:443
            huggingface.co:443
            *.githubusercontent.com:443
            production.cloudflare.docker.com:443
            proxy.golang.org:443
            registry-1.docker.io:443
            storage.googleapis.com:443
            deb.debian.org:80
            developer.download.nvidia.com:443
            get.helm.sh:443
            *.blob.core.windows.net:443
            *.azureedge.net:443
            registry.k8s.io:443
            *.pkg.dev:443
            *.amazonaws.com:443
            dl-cdn.alpinelinux.org:443
            ghcr.io:443

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      # need containerd image store for testing local images
      - uses: crazy-max/ghaction-setup-docker@78318f8be53384b971671f27d81f5e72526c102d # v3.3.0
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - uses: crazy-max/ghaction-github-runtime@b3a9207c0e1ef41f4cf215303c976869d0c2c1c4 # v3.0.0

      - name: build aikit
        run: |
          docker buildx build . -t aikit:test \
            --load --provenance=false --progress plain \
            --cache-from=type=gha,scope=aikit \
            --cache-to=type=gha,scope=aikit,mode=max

      - name: build test model
        run: |
          docker buildx build . -t testmodel:test \
            -f test/aikitfile-llama.yaml \
            --load --provenance=false --progress plain \
            --cache-from=type=gha,scope=testmodel \
            --cache-to=type=gha,scope=testmodel,mode=max

      - name: list images
        run: docker images

      - name: install e2e dependencies
        run: make test-e2e-dependencies

      - name: create kind cluster
        run: kind create cluster --wait 5m

      - name: load test model image into kind cluster
        run: kind load docker-image testmodel:test

      - name: deploy test model
        run: |
          helm install charts/aikit --wait --debug \
            --name-template aikit --namespace aikit --create-namespace \
            --set image.repository=testmodel \
            --set image.tag=test \
            --set image.pullPolicy=Never
          kubectl port-forward -n aikit service/aikit 8080:8080 &

      - name: run test
        run: |
          result=$(curl --fail --retry 10 --retry-all-errors http://127.0.0.1:8080/v1/chat/completions -H "Content-Type: application/json" -d '{
            "model": "llama-3.1-8b-instruct",
            "messages": [{"role": "user", "content": "explain kubernetes in a sentence"}]
          }')
          echo $result

          choices=$(echo "$result" | jq '.choices')
          if [ -z "$choices" ]; then
            exit 1
          fi

      - name: save logs
        if: always()
        run: |
          echo "KIND_LOGS_PATH=$(kind export logs)" >> $GITHUB_ENV

      - name: publish logs
        if: always()
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: kind-logs
          path: $KIND_LOGS_PATH
